
package com.beyond.util.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://service.webservice.util.beyond.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param hybHeader
     * @param parameters
     * @return
     *     returns com.beyond.util.webservice.client.HYBMethodResponse
     */
    @WebMethod(operationName = "HYBMethod")
    @WebResult(name = "HYBMethodResponse", targetNamespace = "http://service.webservice.util.beyond.com/", partName = "result")
    @Action(input = "http://service.webservice.util.beyond.com/Hello/HYBMethodRequest", output = "http://service.webservice.util.beyond.com/Hello/HYBMethodResponse")
    public HYBMethodResponse hybMethod(
            @WebParam(name = "HYBMethod", targetNamespace = "http://service.webservice.util.beyond.com/", partName = "parameters")
                    HYBMethod parameters,
            @WebParam(name = "HYBHeader", targetNamespace = "http://service.webservice.util.beyond.com/", header = true, partName = "HYBHeader")
                    String hybHeader);

}
