
package com.beyond.util.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HYBService", targetNamespace = "http://service.webservice.util.beyond.com/", wsdlLocation = "http://localhost:8080/HYBService?wsdl")
public class HYBService
    extends Service
{

    private final static URL HYBSERVICE_WSDL_LOCATION;
    private final static WebServiceException HYBSERVICE_EXCEPTION;
    private final static QName HYBSERVICE_QNAME = new QName("http://service.webservice.util.beyond.com/", "HYBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/HYBService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HYBSERVICE_WSDL_LOCATION = url;
        HYBSERVICE_EXCEPTION = e;
    }

    public HYBService() {
        super(__getWsdlLocation(), HYBSERVICE_QNAME);
    }

    public HYBService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HYBSERVICE_QNAME, features);
    }

    public HYBService(URL wsdlLocation) {
        super(wsdlLocation, HYBSERVICE_QNAME);
    }

    public HYBService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HYBSERVICE_QNAME, features);
    }

    public HYBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HYBService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort() {
        return super.getPort(new QName("http://service.webservice.util.beyond.com/", "HelloPort"), Hello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.util.beyond.com/", "HelloPort"), Hello.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HYBSERVICE_EXCEPTION!= null) {
            throw HYBSERVICE_EXCEPTION;
        }
        return HYBSERVICE_WSDL_LOCATION;
    }

}
